apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  PORT: {{ .Values.env.PORT | quote }}
